<?php /* Copyright (c) 2012, Derrick Coetzee (User:Dcoetzee)
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

include 'common.php';

# Get starting time to measure time elapsed later.
$time_start = microtime_float();
connect_to_database();
header("Content-Type: text/html; charset=utf-8");
$user_name = wiki_decode(sanitize_username($_GET['username']));
$user_name_html = htmlspecialchars($user_name);
$user_name_url = wiki_urlencode($user_name);

echo <<<EOT
<html><head><title>Users following $user_name_html</title>
<link rel="stylesheet" type="text/css" href="class.css" />
</head>
<body>
<h1>Users following <a href="//en.wikipedia.org/wiki/User:$user_name_url">$user_name_html</a></h1>
EOT;

list ($user_id, $user_text) = get_user_id_and_text($user_name);

if ($user_id != 0) {
  print "<p><a href=\"followedby.php?username=$user_name_url\">View users followed by $user_name_html</a></p>";
}

$back_message = '<p><a href=".">Return to main Followed users page</a></p>';
print $back_message;

create_tables();
$query = "SELECT user_name FROM " . $followed_users_table . " INNER JOIN user ON following_follower=user_id " .
  "WHERE following_followee = " . $user_id . " " .
  "AND following_followee_text = " . $user_text . " " .
  "ORDER BY user_name";
$result = mysql_query($query) or die(mysql_error());
$entries = array();
print '<ul>';
$none = true;
while ($row = mysql_fetch_array($result)) {
  $follower_name_url = wiki_urlencode($row['user_name']);
  print '<li><a href="//en.wikipedia.org/wiki/User:' . $follower_name_url . '">' . htmlspecialchars(wiki_decode($row['user_name'])) . '</a> [<a href="followedby.php?username=' . $follower_name_url . '">all following</a>]</li>';
  $none = false;
}
if ($none) {
  print "<p>User has no followers at the present time.</p>";
}
print '</ul>';

print $back_message;

$time_delta = microtime_float() - $time_start;
printf('<p><small>This report generated by <a href="//toolserver.org/~dcoetzee/followedusers/following.php?username=' . $user_name_url . '">Followed users</a> at ' . date('c')  . ' in %0.2f sec.</small></p>', $time_delta);

echo '</body></html>';

?>